### PR TITLE
Upgrade helm charts too

### PR DESCRIPTION
**Pull request by ericvaandering**
For this release, it's just a version number change. No difference from the last version in 34.0

### CODE REVIEW

**Review by dynamic-entropy — COMMENTED** [review]
Hello @ericvaandering 

Any particular reason that this is not merged?

Also, why is the lower chart version kept at 34?

**Comment by ericvaandering** [comment]
No reason except that I was testing it the day before I left for 1.5 weeks and there were no actual changes to the helm charts, just version numbers. :-)

I kept the lower bound just in case there were not actually 35.x helm charts for something.

**Comment by dynamic-entropy** [comment]
Thank you, Eric. 
FYI @eachristgr, please confirm if we have the new charts with `--ignore_availability`

**Comment by eachristgr** [comment]
Thank you Eric.

The changes where propagated to the cluster. https://github.com/dmwm/rucio-flux/pull/337 should append `--ignore-availability` to conveyor-preparer.

**Pull request merged**
