### PR TITLE
Update CC endpoint

### PR DESCRIPTION
**Pull request by guyzsarun**

### CODE REVIEW

**Comment by dynamic-entropy** [comment]
Hello @guyzsarun 
Do you want to do it using the RSE attributes?
https://github.com/ivmfnal/cms_consistency/tree/master/site_cmp3#parameters-controlled-by-site-admin

Later, we can define RSE attributes that site-admins can modify as part of https://github.com/ivmfnal/cms_consistency/tree/master/site_cmp3#parameters-controlled-by-site-admin

**Comment by guyzsarun** [comment]
Hello @dynamic-entropy ,
Forgive my ignorance, but considering that all the necessary information for CE is available in Rucio, Is there any reason not to use the xrootd protocol defined on each RSE to avoid duplication?

**Comment by dynamic-entropy** [comment]
Hello @guyzsarun , 
Not all sites provide a root endpoint for transfer operations, and only exclusively for file listings by CC. @ivmfnal or @ericvaandering can correct me if I am mistaken on the "exclusive" part. 
An e.g. would be `T2_IT_Bari`.
So to keep it simpler they are defined separately.

**Comment by dynamic-entropy** [comment]
@guyzsarun Please reopen if something else is required here.

**Pull request closed without merging**
