### PR TITLE
Adapt KIT setup to new split doors + enable checks for KIT tape

### PR DESCRIPTION
**Pull request by ArturAkh**
Dear all,

This is a pull request to adapt T1_DE_KIT setup for consistency checks to the dCache doors, which will be split into disk and tape.

This also allows to run consistency checks for T1_DE_KIT_Tape in addition.

To be merged during the KIT Downtime on 6th+7th December.

Best regards,

Artur

### CODE REVIEW

**Review by dynamic-entropy — APPROVED** [review]
Hello @ArturAkh 
I am merging this.

FYI, you can control consistency check settings using RSE attributes
https://github.com/ivmfnal/cms_consistency/tree/master/site_cmp3#parameters-controlled-by-site-admin

**Comment by ArturAkh** [comment]
Hi @dynamic-entropy,

Thanks a lot! I'll have a look at the documentation.

Would a change via the RSE attributes also be automatically submitted to this repository?

**Comment by dynamic-entropy** [comment]
Hi Artur
It won't be submitted to the directory. The rse attribute configurations simply override the ones in this repo.

**Comment by ArturAkh** [comment]
Ah OK, thanks for clarification!

**Pull request merged**
