### PR TITLE
Update prod-consistency-jobs.yaml for KIT

### PR DESCRIPTION
**Pull request by ArturAkh**
Adjust the dCache XRootD entry-point server names for T1_DE_KIT according to latest status.

### CODE REVIEW

**Review by dynamic-entropy — APPROVED** [review]
Hello Artur Thankyou

Can you check if you have permissions to edit the rse attributes? To configure CE?

https://github.com/dmwm/cms_consistency/tree/7e76220eadc20d90f3538160e6d524a1e986ba5c/site_cmp3#parameters-controlled-by-site-admin

**Comment by ArturAkh** [comment]
Hi @dynamic-entropy,

I've tried the following with my VOMS certificate:

```bash
arturgo@arturgo-ThinkPad-P14s-Gen-2i:~/dc2hpss$ rucio-admin rse set-attribute --rse T1_DE_KIT_Disk --key CE_config.server --value cmsdcache-kit-disk.gridka.de:1094 
Access to the requested resource denied.
Details: Account aakhmets can not add RSE attributes
This error is a permission issue. You cannot run this command with your account.
```

But it failed.

**Comment by dynamic-entropy** [comment]
Thankyou Artur
I will run it for you for now. 
And add this to my list of attributes to expose to site admins.

**Comment by ArturAkh** [comment]
OK, thanks a lot, Rahul!

**Comment by dynamic-entropy** [comment]
```
➜  ~ rucio-admin rse set-attribute --rse T1_DE_KIT_Disk --key CE_config.server --value cmsdcache-kit-disk.gridka.de:1094 
Added new RSE attribute for T1_DE_KIT_Disk: CE_config.server-cmsdcache-kit-disk.gridka.de:1094 
➜  ~ rucio-admin rse set-attribute --rse T1_DE_KIT_Tape --key CE_config.server --value cmsdcache-kit-tape.gridka.de:1094 
Added new RSE attribute for T1_DE_KIT_Tape: CE_config.server-cmsdcache-kit-tape.gridka.de:1094
```

There you go.

**Pull request closed without merging**
