### PR TITLE
UCSD Migration to CEPH. Change of endpoint.

### PR DESCRIPTION
**Pull request by FernandoGarzon**

### CODE REVIEW

**Comment by ericvaandering** [comment]
If you are changing the endpoint for UCSD how do you know what the threshold should be set at? I am very nervous about 90% missing thresholds.

**Comment by FernandoGarzon** [comment]
Because they are migrating their file system, then I would expect a huge missing fraction. However, we can just let the cc run and then change the fraction when we have the exact number.

**Comment by ericvaandering** [comment]
Up to you and them. Can you just check and confirm which path you want to take?

**Comment by FernandoGarzon** [comment]
90% is good. Let's keep the PR as is and see how it goes.

**Pull request merged**
